spring.application.name=mybatis_test

# H2 DB 접속 정보 (인메모리 모드)
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=

# H2 웹 콘솔 접속 설정
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console